In [4]:
import torch

x = torch.Tensor([[[1,3,5],[2,4,6]]])
x.shape

torch.Size([1, 2, 3])

In [5]:
x[:,1,:].repeat(1,2,1)

tensor([[[2., 4., 6.],
         [2., 4., 6.]]])

In [6]:
x.repeat_interleave(2,1)

tensor([[[1., 3., 5.],
         [1., 3., 5.],
         [2., 4., 6.],
         [2., 4., 6.]]])

In [7]:
x.repeat(1,2,1)

tensor([[[1., 3., 5.],
         [2., 4., 6.],
         [1., 3., 5.],
         [2., 4., 6.]]])

In [8]:
x.repeat(1,2,1).shape

torch.Size([1, 4, 3])

In [11]:
x.repeat(1,1,2).reshape((1,4,3))

tensor([[[1., 3., 5.],
         [1., 3., 5.],
         [2., 4., 6.],
         [2., 4., 6.]]])